services:
  web:
    build: .
    ports:
      - "8099:8099"
    volumes:
      - "./src:/srv/app"
    environment:
      FLASK_DEBUG: "true"

  db:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pytask
      MYSQL_USER: chatdbuser
      MYSQL_PASSWORD: Heute0000
    volumes:
      - ./db:/var/lib/mysql
      - ./db-init.db:/docker-entrypoint-initdb.d/init.sql