services:
  web:
    build: .
    ports:
      - "8069:8069"
    volumes:
      - "./src:/srv/app"
    environment:
      FLASK_DEBUG: "true"
      DATABASE_URL: "mysql+pymysql://root:root@db/pytaskdb" 
    networks:
      - pytask-backend

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pytaskdb
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
    volumes:
      - ./db:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pytask-backend

networks:
  pytask-backend: